### ISSUE TITLE
Install working? Grunt requirement conflicts? Node 7.3

### ISSUE THREAD

**Issue by idkjs** [tilomitra/bedrock#4]
I came across your project and thought I would check it out. I followed the quickstart instruction and i'm getting the following errors. Looks like the project has conflicting grunt requirements. Here is the console output. 
```
npm WARN grunt-debug-task@0.1.8 requires a peer of grunt@~0.4.2 but none was installed.
npm WARN grunt-react@0.12.3 requires a peer of grunt@~0.4.2 but none was installed.
npm WARN Bedrock@2.2.0 No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/klik/.nvm/versions/node/v7.3.0/bin/node" "/Users/klik/.nvm/versions/node/v7.3.0/bin/npm" "install"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/klik/Projects/Bedrock/bedrock-starter/npm-debug.log
klik:bedrock-starter klik$ 
```

**Comment by tilomitra** [comment]
Could you try on Node v6.x? I haven't tested this on v7 yet. I'll go ahead and do that, but it'll take me a few days.

**Comment by idkjs** [comment]
ok. Running with node 6.3 now. Terminal output below. Notice how it keeps asking for different versions of grunt. Specifically .04.2 and then 1.0.1 which you cant install at the same time.

```bash
npm WARN grunt-debug-task@0.1.8 requires a peer of grunt@~0.4.2 but none was installed.
npm WARN grunt-react@0.12.3 requires a peer of grunt@~0.4.2 but none was installed.
npm WARN Bedrock@2.2.0 No license field.
klik:bedrock-starter klik$ code-insiders .
klik:bedrock-starter klik$ npm install sails-mysql 
Bedrock@2.2.0 /Users/klik/Projects/Bedrock/bedrock-starter
├── UNMET PEER DEPENDENCY grunt@1.0.1
└── sails-mysql@0.11.5 

npm WARN grunt-debug-task@0.1.8 requires a peer of grunt@~0.4.2 but none was installed.
npm WARN grunt-react@0.12.3 requires a peer of grunt@~0.4.2 but none was installed.
npm WARN Bedrock@2.2.0 No license field.
klik:bedrock-starter klik$ npm install grunt --save-dev
Bedrock@2.2.0 /Users/klik/Projects/Bedrock/bedrock-starter
└── UNMET PEER DEPENDENCY grunt@1.0.1

npm WARN grunt-debug-task@0.1.8 requires a peer of grunt@~0.4.2 but none was installed.
npm WARN grunt-react@0.12.3 requires a peer of grunt@~0.4.2 but none was installed.
npm WARN Bedrock@2.2.0 No license field.
npm ERR! code 1
klik:bedrock-starter klik$ 
```

**Comment by tilomitra** [comment]
Yep, I'll clean up the grunt output. Is the server running though?

**Comment by idkjs** [comment]
klik:bedrock-starter klik$ node app.js 
verbose: logger hook loaded successfully.
verbose: request hook loaded successfully.
verbose: Loading the app's models and adapters...
verbose: Loading app models...
verbose: Loading app adapters...
warn: Using Handlebars v3.x; Versions < 4.0.0 may introduce security risks (see https://snyk.io/test/npm/handlebars/3).
warn: When an updated version becomes available, you should be able to install it by updating your copy of Sails with `npm update`.
verbose: Loading blueprint middleware...
verbose: blueprints hook loaded successfully.
verbose: responses hook loaded successfully.
verbose: controllers hook loaded successfully.
verbose: Loading policy modules from app...
verbose: Finished loading policy middleware logic.
verbose: policies hook loaded successfully.
verbose: services hook loaded successfully.
verbose: csrf hook loaded successfully.
verbose: cors hook loaded successfully.
verbose: i18n hook loaded successfully.
verbose: session hook loaded successfully.
verbose: Loading app Gruntfile...
verbose: Tracking new grunt child process...
verbose: grunt hook loaded successfully.
verbose: http hook loaded successfully.
verbose: Overriding handlebars engine with express-handlebars to implement layout support...
verbose: Preparing socket.io...
verbose: sockets hook loaded successfully.
verbose: Loading adapter ( sails-mysql ) for passport  from `node_modules` directory...
verbose: views hook loaded successfully.
verbose: Setting default Express view engine to handlebars...
verbose: Starting ORM...
verbose: orm hook loaded successfully.
verbose: pubsub hook loaded successfully.
verbose: Built-in hooks are ready.
verbose: Instantiating registry...
verbose: Loading router...
verbose: Policy-controller bindings complete!
verbose: All hooks were loaded successfully.
verbose: Starting app at /Users/klik/Projects/Bedrock/bedrock-starter...
verbose: Running the setup logic in `sails.config.bootstrap(cb)`...
info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.11.5             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/Users/klik/Projects/Bedrock/bedrock-starter`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Mon Jan 16 2017 11:02:18 GMT+0100 (CET)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
verbose: sails-hook-sockets :: connected to Sails admin message bus.

**Comment by matthova** [comment]
Was about to open an issue, but I see one was already made. Still having running 'npm install' without an error with node v7.6.0. Should I open a new issue "run npm install without error on v7" or will reopening this issue cover it?
